
-- CUSTOMISATION D'ARMES 

-- local selected = nil;

-- Alma.newThread(function()
--     while (true) do
--         Citizen.Wait(1000)
--         local weapon = GetSelectedPedWeapon(PlayerPedId());
--         if (weapon ~= GetHashKey("weapon_unarmed")) and (weapon ~= 966099553) and (weapon ~= 0) then
--             if (selected ~= nil) and (weapon == GetHashKey("weapon_unarmed")) and (weapon == 966099553) and (weapon == 0) then
--                 selected = nil;
--             end
--             selected = ESX.GetWeaponFromHash(GetHashKey(weapon))
--         else
--             selected = nil;
--         end

--     end
-- end)

-- function OpenCustomArmes()
--     local BoutiqueSub = RageUI.CreateMenu('Boutique Alma', "Bienvenue sur notre boutique")
--     BoutiqueSub.onIndexChange = function(index)
--         if (selected ~= nil) then
--             GiveWeaponComponentToPed(PlayerPedId(), GetHashKey(selected.name), selected.components[index].hash)
--             if (selected.components[index - 1] ~= nil) and (selected.components[index - 1].hash ~= nil) then
--                 RemoveWeaponComponentFromPed(PlayerPedId(), GetHashKey(selected.name), selected.components[index - 1].hash)
--             end
--             if (index == 1) then
--                 RemoveWeaponComponentFromPed(PlayerPedId(), GetHashKey(selected.name), selected.components[#selected.components].hash)
--             end
--         end
--     end
--     RageUI.Visible(BoutiqueSub, not RageUI.Visible(BoutiqueSub))
--     while BoutiqueSub do
--         Citizen.Wait(0)
--         RageUI.IsVisible(BoutiqueSub, function()
--             if (selected) then
--                 if (ESX.Table.SizeOf(selected) > 0) then
--                     for i, v in pairs(selected.components) do
--                         RageUI.Button(v.label, nil, { RightLabel = "250", RightBadge = RageUI.BadgeStyle.Tick }, true, {
--                             onSelected = function()
--                                 variable = KeyboardInput('Veuillez confirmer l\'achat (~g~Oui~s~/~r~Non~s~)', ('Veuillez confirmer l\'achat (~g~Oui~s~/~r~Non~s~)'), '', 30)
--                                 if variable == 'OUI' or variable == 'oui' or variable:lower() == "oui" or variable:upper() == "OUI" then
--                                     AlmaUtils.toServer('tebex:on-process-checkout-weapon-custom', selected.name, v.hash)
--                                     ESX.ShowAdvancedNotification('AlmaRP', '~y~Boutique', 'Vous avez acheter '..v.label.. ' pour 250 ~r~AlmaCoins', 'CHAR_CALIFORNIA', 9)
--                                 else
--                                     ESX.ShowNotification('~r~Vous avez annulez l\'achat')
--                                 end
--                             end,
--                         })
--                     end
--                 else
--                     RageUI.Separator("Aucune personnalisation disponible")
--                 end
--             else
--                 RageUI.Separator("Vous n'avez pas d'arme dans vos main")
--             end
--         end, function()
--         end)

--         if not RageUI.Visible(BoutiqueSub) then
--             OpenBoutique()
--             TriggerEvent('esx:restoreLoadout')
--             BoutiqueSub = RMenu:DeleteType('BoutiqueSub', true)
--         end
--     end
-- end

-- Alma.netRegisterAndHandle("cstmMenu", function()
--     Wait(150)
--     RageUI.Visible(wp, true)
-- end)
