WeaponBoutique = {
  {label = 'Sabre Laser', name = 'WEAPON_HATCHET', description = nil, price = 500},
  {label = 'Katana', name = 'WEAPON_BAT', description = nil, price = 500},
  {label = 'Pistolet Cal.50', name = 'WEAPON_PISTOL50', description = nil, price = 1000},
  {label = 'Pistolet Mitrailleur', name = 'WEAPON_MICROSMG', description = nil, price = 1500},
  {label = 'AK-47', name = 'WEAPON_ASSAULTRIFLE', description = nil, price = 3000},
  {label = 'G36-C Custom', name = 'WEAPON_SPECIALCARBINE', description = nil, price = 3500},
}

SecurityWeapons = {
    ['WEAPON_HATCHET'] = {price = 500, name = 'WEAPON_HATCHET', label = 'Sabre Laser'},
    ['WEAPON_BAT'] = {price = 500, name = 'WEAPON_BAT',label = 'Katana'},
    ['WEAPON_PISTOL50'] = {price = 1000, name = 'WEAPON_PISTOL50',label = 'Pistolet Cal.50'},
    ['WEAPON_MICROSMG'] = {price = 1500, name = 'WEAPON_MICROSMG',label = 'Pistolet Mitrailleur'},
    ['WEAPON_ASSAULTRIFLE'] = {price = 3000, name = 'WEAPON_ASSAULTRIFLE',label = 'AK-47'},
    ['WEAPON_SPECIALCARBINE'] = {price = 3500, name = 'WEAPON_SPECIALCARBINE',label = 'G36-C Custom'},
}

-- @TODO Vehicles

BoutiqueVehicles = {
    {label = 'Golf Mk7', model = 'rmodmk7', description = nil, price = 2500},
    {label = 'Toyota Supra', model = 'rmodsuprapandem', description = nil, price = 3500},
    {label = 'Rolls Dawnonyx', model = 'dawnonyx', description = nil, price = 3000},
    {label = 'Porsche 918', model = 'rmodporsche918', description = nil, price = 2500},
    {label = 'Porsche 911 Turbo', model = '911turbos', description = nil, price = 5000},
    {label = 'Nissan Skyline', model = 'rmodskyline34', description = nil, price = 4000},
    {label = 'Nissan GTR', model = 'rmodgtr50', description = nil, price = 3000},
    {label = 'Nissan Fairlady', model = 'rmodz350pandem', description = nil, price = 3500},
    {label = 'Nissan 240SX', model = 'rmod240sx', description = nil, price = 2500},
    {label = 'Mercedes G65 AMG', model = 'rmodg65', description = nil, price = 3000},
    {label = 'Mercedes E63S', model = 'rmode63s', description = nil, price = 2500},
    {label = 'Mercedes C63 AMG', model = 'rmodc63amg', description = nil, price = 2000},
    {label = 'Mercedes A45', model = 'a45', description = nil, price = 2500},
    {label = 'McLaren Senna', model = 'rmodsennagtr', description = nil, price = 3500},
    {label = 'McLaren P1', model = 'rmodp1gtr', description = nil, price = 2500},
    {label = 'Lamborghini Sian', model = 'rmodsianr', description = nil, price = 4000},
    {label = 'Lamborghini Murciélago', model = 'rmodlp670', description = nil, price = 3000},
    {label = 'Lamborghini Essenza', model = 'rmodessenza', description = nil, price = 4000},
    {label = 'Jeep Cherokee', model = 'rmodjeep', description = nil, price = 1500},
    {label = 'Fiat 500 Abarth', model = 'rmodbiposto', description = nil, price = 1500},
    {label = 'Ferrari F12', model = 'rmodf12tdf', description = nil, price = 3000},
    {label = 'BMW M4', model = 'rmodm4gts', description = nil, price = 2000},
    {label = 'BMW i8', model = 'rmoddarki8', description = nil, price = 3000},
    {label = 'BMW i8 Coupe', model = 'rmodi8ks', description = nil, price = 2500},
    {label = 'Bugatti Chiron', model = 'rmodchiron300', description = nil, price = 3000},
    {label = 'Bugatti Bolide', model = 'rmodbolide', description = nil, price = 3000},
    {label = 'Bugatti', model = 'rmodbugatti', description = nil, price = 3000},
    {label = 'Bentley GT', model = 'rmodbentleygt', description = nil, price = 2000},
    {label = 'Bentley Bacalar', model = 'rmodbacalar', description = nil, price = 2000},
    {label = 'Bentley 1', model = 'rmodbentley1', description = nil, price = 2000},
    {label = 'Audi RS6', model = 'rmodrs6', description = nil, price = 2000},
    {label = 'Aston Martin', model = 'rmodmartin', description = nil, price = 3000},
}

SecurityVehicles = {
    ['rmodmk7'] = {label = 'Golf Mk7', model = 'rmodmk7', description = nil, price = 2500},
    ['rmodsuprapandem'] = {label = 'Toyota Supra', model = 'rmodsuprapandem', description = nil, price = 3500},
    ['dawnonyx'] = {label = 'Rolls Dawnonyx', model = 'dawnonyx', description = nil, price = 3000},
    ['rmodporsche918'] = {label = 'Porsche 918', model = 'rmodporsche918', description = nil, price = 2500},
    ['911turbos'] = {label = 'Porsche 911 Turbo', model = '911turbos', description = nil, price = 5000},
    ['rmodskyline34'] = {label = 'Nissan Skyline', model = 'rmodskyline34', description = nil, price = 4000},
    ['rmodgtr50'] = {label = 'Nissan GTR', model = 'rmodgtr50', description = nil, price = 3000},
    ['rmodz350pandem'] = {label = 'Nissan Fairlady', model = 'rmodz350pandem', description = nil, price = 3500},
    ['rmod240sx'] = {label = 'Nissan 240SX', model = 'rmod240sx', description = nil, price = 2500},
    ['rmodg65'] = {label = 'Mercedes G65 AMG', model = 'rmodg65', description = nil, price = 3000},
    ['rmode63s'] = {label = 'Mercedes E63S', model = 'rmode63s', description = nil, price = 2500},
    ['rmodc63amg'] = {label = 'Mercedes C63 AMG', model = 'rmodc63amg', description = nil, price = 2000},
    ['a45'] = {label = 'Mercedes A45', model = 'a45', description = nil, price = 2500},
    ['rmodsennagtr'] = {label = 'McLaren Senna', model = 'rmodsennagtr', description = nil, price = 3500},
    ['rmodp1gtr'] = {label = 'McLaren P1', model = 'rmodp1gtr', description = nil, price = 2500},
    ['rmodsianr'] = {label = 'Lamborghini Sian', model = 'rmodsianr', description = nil, price = 4000},
    ['rmodlp670'] = {label = 'Lamborghini Murciélago', model = 'rmodlp670', description = nil, price = 3000},
    ['rmodessenza'] = {label = 'Lamborghini Essenza', model = 'rmodessenza', description = nil, price = 4000},
    ['rmodjeep'] = {label = 'Jeep Cherokee', model = 'rmodjeep', description = nil, price = 1500},
    ['rmodbiposto'] = {label = 'Fiat 500 Abarth', model = 'rmodbiposto', description = nil, price = 1500},
    ['rmodf12tdf'] = {label = 'Ferrari F12', model = 'rmodf12tdf', description = nil, price = 3000},
    ['rmodm4gts'] = {label = 'BMW M4', model = 'rmodm4gts', description = nil, price = 2000},
    ['rmoddarki8'] = {label = 'BMW i8', model = 'rmoddarki8', description = nil, price = 3000},
    ['rmodi8ks'] = {label = 'BMW i8 Coupe', model = 'rmodi8ks', description = nil, price = 2500},
    ['rmodchiron300'] = {label = 'Bugatti Chiron', model = 'rmodchiron300', description = nil, price = 3000},
    ['rmodbolide'] = {label = 'Bugatti Bolide', model = 'rmodbolide', description = nil, price = 3000},
    ['rmodbugatti'] = {label = 'Bugatti', model = 'rmodbugatti', description = nil, price = 3000},
    ['rmodbentleygt'] = {label = 'Bentley GT', model = 'rmodbentleygt', description = nil, price = 2000},
    ['rmodbacalar'] = {label = 'Bentley Bacalar', model = 'rmodbacalar', description = nil, price = 2000},
    ['rmodbentley1'] = {label = 'Bentley 1', model = 'rmodbentley1', description = nil, price = 2000},
    ['rmodrs6'] = {label = 'Audi RS6', model = 'rmodrs6', description = nil, price = 2000},
    ['rmodmartin'] = {label = 'Aston Martin', model = 'rmodmartin', description = nil, price = 3000},
    ['kx450f'] = {label = 'Kawa 450F', model = 'kx450f', description = nil, price = 1500},

}

BoutiqueMysteryBox = {
    {label = 'Caisse Gold', description = 'Prix : 1000 ~r~Alma~w~Coins', model = 3, description = nil, rightlabel = nil, price = 1000},
    {label = 'Caise Diamond', description = 'Prix : 3000 ~r~Alma~w~Coins', model = 2, description = nil, rightlabel = nil,  price = 3000},
    {label = 'Caisse Ruby',description = 'Prix : 5000 ~r~Alma~w~Coins', model = 1, description = nil, rightlabel = nil,  price = 5000},
    --{label = '[BIENTOT] - Caisse Ete', description = 'Prix : 2500 ~b~Sea~w~Coins',model = 'case_4', description = nil, rightlabel = '~y~Limité',  price = 999999},
}