Concess = {};

Concess.prevPoint = vector3(-791.82904052734,-216.70513916016,37.41442489624)
Concess.prevPoint_heading = 198.0

Concess.vehicles = {
	{
		cat_name = "Commercials",
		value = "commercials",
		vehicles = {
			{name = "Benson", hash = "benson", price = 150000, capacity = 120},
			{name = "Biff", hash = "biff", price = 120000, capacity = 100},
			{name = "Mule", hash = "mule", price = 120000, capacity = 100},
			{name = "Mule 2", hash = "mule2", price = 100000, capacity = 100},
			{name = "Mule 3", hash = "mule3", price = 120000, capacity = 100},
			{name = "Taco", hash = "taco", price = 125000, capacity = 45},
			{name = "Stockade", hash = "stockade", price = 100000, capacity = 80},
		},
	},
	{
		cat_name = "Compacts",
		value = "compacts",
		vehicles = {
			{name = "Blista", hash = "blista", price = 8000, capacity = 30},
			{name = "Blista 2", hash = "blista2", price = 17000, capacity = 35},
			{name = "Blista 3", hash = "blista3", price = 22000, capacity = 35},
			{name = "Brioso", hash = "brioso", price = 9000, capacity = 20},
			{name = "Dilettante", hash = "dilettante", price = 7000, capacity = 30},
			{name = "Issi 2", hash = "issi2", price = 10000, capacity = 20},
			{name = "Panto", hash = "panto", price = 6000, capacity = 20},
			{name = "Prairie", hash = "prairie", price = 7500, capacity = 30},
			{name = "Rhapsody", hash = "rhapsody", price = 5500, capacity = 30},
		},
	},
	{
		cat_name = "Coupes",
		value = "coupes",
		vehicles = {
			{name = "Cognoscenti Cabrio", hash = "cogcabrio", price = 80000, capacity = 30},
			{name = "Exemplar", hash = "exemplar", price = 48000, capacity = 30},
			{name = "F620", hash = "f620", price = 60000, capacity = 30},
			{name = "Felon", hash = "felon", price = 72000, capacity = 30},
			{name = "Felon GT", hash = "felon2", price = 82000, capacity = 20},
			{name = "Jackal", hash = "jackal", price = 55000, capacity = 30},
			{name = "Oracle", hash = "oracle", price = 52000, capacity = 30},
			{name = "Oracle XS", hash = "oracle2", price = 60000, capacity = 30},
			{name = "Sentinel", hash = "sentinel", price = 48000, capacity = 30},
			{name = "Sentinel XS", hash = "sentinel2", price = 60000, capacity = 30},
			{name = "Windsor", hash = "windsor", price = 125000, capacity = 30},
			{name = "Windsor Drop", hash = "windsor2", price = 150000, capacity = 20},
			{name = "Zion", hash = "zion", price = 50000, capacity = 30},
			{name = "Zion Cabrio", hash = "zion2", price = 65000, capacity = 20},
		},
	},
	{
		cat_name = "Industriel",
		value = "industriel",
		vehicles = {
			{name = "Guardian", hash = "guardian", price = 100000, capacity = 80},
			{name = "Rubble", hash = "rubble", price = 90000, capacity = 80},
			{name = "Tip Truck", hash = "tiptruck", price = 90000, capacity = 80},
			{name = "Tip Truck 2", hash = "tiptruck2", price = 90000, capacity = 80},
		},
	},
	-- {
	-- 	cat_name = "Imports",
	-- 	value = "imports",
	-- 	vehicles = {
	-- 		{name = "Audi RS6 WB", hash = "2020rs6", price = 2250000, capacity = 25},
    --         {name = "Audi RS7 WB", hash = "rs7c8wb", price = 2450000, capacity = 25},
    --         {name = "Audi R8 2020", hash = "r820", price = 2250000, capacity = 20},
	-- 		{name = "Bentley Mulliner", hash = "rmodbacalar", price = 4000000, capacity = 25},
    --         {name = "BMW X6", hash = "rmodx6", price = 2750000, capacity = 35},
    --         {name = "BMW Alpinae30", hash = "alpinae30", price = 550000, capacity = 20},
    --         {name = "Bugatti Veyron 2010", hash = "bvit", price = 3250000, capacity = 10},
    --         {name = "Ducati V4S StreetFighter", hash = "v4sf", price = 1750000},
    --         {name = "Jeep Trackhawk", hash = "rmodjeep", price = 3450000, capacity = 45},
	-- 		{name = "Lamborghini Veneno", hash = "veneno", price = 2850000, capacity = 15},
	-- 		{name = "Mercedes GLE2020", hash = "gle53", price = 950000, capacity = 40},
    --         {name = "Mercedes GT63S AMG", hash = "gt63samg", price = 2450000, capacity = 40},
	-- 		{name = "Porsche panamera mansory", hash = "pmansory", price = 2950000, capacity = 40},
    --         {name = "Raptor 2017", hash = "raptor2017", price = 3450000, capacity = 70},
    --         {name = "Raptor 150", hash = "raptor150", price = 3250000, capacity = 50},
    --         {name = "KTM EXC 450 Jaune", hash = "2020exc", price = 225000},
	-- 		{name = "KTM EXC 450 Orange", hash = "2020exco", price = 225000},
	-- 		{name = "Tampa R", hash = "tampar", price = 225000},
    --         {name = "Contender C", hash = "contenderc", price = 225000},
    --         {name = "Buffalo H", hash = "buffaloh", price = 225000},
    --     },
	-- },
	{
		cat_name = "Imports GTA",
		value = "imports GTA",
		vehicles = {
			{name = "Jugular", hash = "jugular", price = 600000, capacity = 25},
			{name = "Caracara 2", hash = "caracara2", price = 600000, capacity = 35},
			{name = "Neo", hash = "neo", price = 400000, capacity = 15},
			{name = "Brioso 2", hash = "brioso2", price = 300000, capacity = 15},
			{name = "Weevil", hash = "weevil", price = 250000, capacity = 10},
			{name = "Krieger", hash = "krieger", price = 500000, capacity = 15},
			{name = "Emerus", hash = "emerus", price = 550000, capacity = 15},
			{name = "Itali RSX", hash = "italirsx", price = 550000, capacity = 10},
            {name = "Zorrusso", hash = "zorrusso", price = 500000, capacity = 15},
        },
	},
	{
		cat_name = "Moto",
		value = "moto",
		vehicles = {
			{name = "Akuma", hash = "akuma", price = 15000},
			{name = "Avarus", hash = "avarus", price = 27000},
			{name = "Bagger", hash = "bagger", price = 20000},
			{name = "Bati 801", hash = "bati", price = 20000},
			{name = "Bati 801 RR", hash = "bati2", price = 30000},
			{name = "BF 400", hash = "bf400", price = 10000},
			{name = "Carbon RS", hash = "carbonrs", price = 55000},
			{name = "Chimera", hash = "chimera", price = 14000},
			{name = "Cliffhanger", hash = "cliffhanger", price = 27000},
			{name = "Daemon", hash = "daemon", price = 17000},
			{name = "Daemon High", hash = "Daemon2", price = 20000},
			{name = "Defiler", hash = "defiler", price = 14000},
			{name = "Deathbike", hash = "deathbike", price = 19000},
			{name = "Diablous", hash = "diablous", price = 25000},
			{name = "Diablous 2", hash = "diablous2", price = 35000},
			{name = "Double", hash = "double", price = 40000},
			{name = "Enduro", hash = "enduro", price = 8000},
			{name = "Esskey", hash = "esskey", price = 6000},
			{name = "Faggio", hash = "faggio", price = 2800},
			{name = "Faggio 2", hash = "faggio2", price = 2800},
			{name = "Faggio 3", hash = "faggio3", price = 2800},
			{name = "FCR", hash = "fcr", price = 25000},
			{name = "FCR 2", hash = "fcr2", price = 35000},
			{name = "Gargoyle", hash = "gargoyle", price = 24000},
			{name = "Hakuchou", hash = "hakuchou", price = 45000},
			{name = "Hakuchou Sport", hash = "hakuchou2", price = 65000},
			{name = "Hexer", hash = "hexer", price = 18000},
			{name = "Innovation", hash = "innovation", price = 32000},
			{name = "Lectro", hash = "lectro", price = 55000},
			{name = "Manchez", hash = "manchez", price = 10600},
			{name = "Nemesis", hash = "nemesis", price = 8500},
			{name = "Nightblade", hash = "nightblade", price = 50000},
			{name = "PCJ 600", hash = "pcj", price = 9000},
			{name = "Ratbike", hash = "ratbike", price = 20000},
			{name = "Ruffian", hash = "ruffian", price = 10000},
			{name = "Sanchez", hash = "sanchez", price = 10600},
			{name = "Sanchez Sport", hash = "sanchez2", price = 10600},
			{name = "Sanctus", hash = "sanctus", price = 50000},
			{name = "Shotaro", hash = "shotaro", price = 150000},
			{name = "Sovereign", hash = "sovereign", price = 32000},
			{name = "Thrust", hash = "thrust", price = 35000},
			{name = "Vader", hash = "vader", price = 10000},
			{name = "Vortex", hash = "vortex", price = 14000},
			{name = "Wolfsbane", hash = "wolfsbane", price = 13000},
			{name = "Zombie ", hash = "zombiea", price = 14000},
			{name = "Zombie Luxuary", hash = "zombieb", price = 18000},
		},
	},
	{
		cat_name = "Muscle",
		value = "muscle",
		vehicles = {
			{name = "Blade", hash = "blade", price = 22000, capacity = 30},	
			{name = "Buccaneer", hash = "buccaneer", price = 27000, capacity = 20},
			{name = "Buccaneer Rider", hash = "buccaneer2", price = 36000, capacity = 20},
			{name = "Chino", hash = "chino", price = 22000, capacity = 20},
			{name = "Chino Luxe", hash = "chino2", price = 28000, capacity = 20},
			{name = "Clique", hash = "clique", price = 25000, capacity = 30},
			{name = "Coquette 3", hash = "coquette3", price = 80000, capacity = 30},
			{name = "Deviant", hash = "deviant", price = 55000, capacity = 20},
			{name = "Dominator", hash = "dominator", price = 50000, capacity = 30},
			{name = "Dominator GT", hash = "dominator2", price = 63000, capacity = 30},
			{name = "Dominator GTX", hash = "Dominator3", price = 65000, capacity = 30},
			{name = "Dukes", hash = "dukes", price = 41000, capacity = 20},
			{name = "Faction", hash = "faction", price = 30000, capacity = 30},
			{name = "Faction Rider", hash = "faction2", price = 45000, capacity = 30},
			{name = "Faction XL", hash = "faction3", price = 60000, capacity = 30},
			{name = "Ellie", hash = "ellie", price = 35000, capacity = 30},
			{name = "Gauntlet", hash = "gauntlet", price = 42000, capacity = 30},
			{name = "Gauntlet 2", hash = "gauntlet2", price = 50000, capacity = 30},
			{name = "Hermes", hash = "hermes", price = 85000, capacity = 20},
			{name = "Hotknife", hash = "hotknife", price = 150000, capacity = 20},
			{name = "Hustler", hash = "hustler", price = 100000, capacity = 20},
			{name = "Impaler", hash = "impaler", price = 25000, capacity = 30},
			{name = "Impaler 2", hash = "impaler2", price = 30000, capacity = 30},
			{name = "Impaler 3", hash = "impaler3", price = 35000, capacity = 30},
			{name = "Imperator", hash = "imperator", price = 45000, capacity = 30},
			{name = "Moonbeam", hash = "moonbeam", price = 65000, capacity = 50},
			{name = "Moonbeam Rider", hash = "moonbeam2", price = 75000, capacity = 50},
			{name = "Nightshade", hash = "nightshade", price = 95000, capacity = 30},
			{name = "Peyote 2", hash = "peyote2", price = 85000, capacity = 40},
			{name = "Phoenix", hash = "phoenix", price = 25000, capacity = 30},
			{name = "Picador", hash = "picador", price = 27000, capacity = 50},
			{name = "Ratloader", hash = "ratloader", price = 35000, capacity = 30},
			{name = "Ratloader 2", hash = "ratloader2", price = 50000, capacity = 50},
			{name = "Ruiner", hash = "ruiner", price = 29000, capacity = 40},
			{name = "Sabre GT", hash = "sabregt", price = 37000, capacity = 30},
			{name = "Sabre Turbo", hash = "sabregt2", price = 35000, capacity = 30},
			{name = "Slamvan", hash = "slamvan", price = 20000, capacity = 50},
			{name = "Slamvan 2", hash = "slamvan2", price = 22000, capacity = 50},
			{name = "Slamvan 3", hash = "slamvan3", price = 27500, capacity = 50},
			{name = "Stalion", hash = "stalion", price = 37000, capacity = 30},
			{name = "Tampa", hash = "tampa", price = 35000, capacity = 20},
			{name = "Tulip", hash = "tulip", price = 37500, capacity = 30},
			{name = "Vamos", hash = "vamos", price = 42500, capacity = 30},
			{name = "Vigero", hash = "vigero", price = 18000, capacity = 30},
			{name = "Virgo", hash = "virgo", price = 20000, capacity = 40},
			{name = "Virgo 2", hash = "virgo2", price = 29000, capacity = 40},
			{name = "Virgo 3", hash = "virgo3", price = 39000, capacity = 40},
			{name = "Voodoo", hash = "voodoo", price = 20000, capacity = 30},
			{name = "Voodoo 2", hash = "voodoo2", price = 14000, capacity = 30},
			{name = "Yosemite", hash = "yosemite", price = 50000, capacity = 50},
		},
	},
	{
		cat_name = "Off-Road",
		value = "offroad",
		vehicles = {
			{name = "BF Injection", hash = "bfinjection", price = 24000, capacity = 20},
			{name = "Bifta", hash = "bifta", price = 30000, capacity = 20},
			{name = "Blazer", hash = "blazer", price = 15000},
			{name = "Blazer 3", hash = "blazer3", price = 17500},
			{name = "Blazer 4", hash = "blazer4", price = 25000},
			{name = "Bodhi 2", hash = "bodhi2", price = 75000, capacity = 50},
			{name = "Brawler", hash = "brawler", price = 65000, capacity = 30},
			{name = "Brutus", hash = "brutus", price = 150000, capacity = 60},
			{name = "Duneloader", hash = "dloader", price = 55000, capacity = 40},
			{name = "Dubsta 3", hash = "dubsta3", price = 150000, capacity = 80},
			{name = "Dune", hash = "dune", price = 15000, capacity = 20},
			{name = "Freecrawler", hash = "freecrawler", price = 75000, capacity = 50},
			{name = "Kalahari", hash = "kalahari", price = 55000, capacity = 45},
			{name = "Kamacho", hash = "kamacho", price = 200000, capacity = 80},
			{name = "Mesa Trail", hash = "mesa3", price = 75000, capacity = 50},
			{name = "Rancher XL", hash = "rancherxl", price = 80000, capacity = 50},
			{name = "Rebel", hash = "rebel", price = 50000, capacity = 50},
			{name = "Rebel 2", hash = "rebel2", price = 65000, capacity = 50},
			{name = "Riata", hash = "riata", price = 85000, capacity = 50},
			{name = "Sandking", hash = "sandking", price = 150000, capacity = 80},
			{name = "Sandking2", hash = "sandking2", price = 200000, capacity = 80},
			{name = "Trophy Truck", hash = "trophytruck", price = 85000, capacity =20 },
			{name = "Trophy Truck 2", hash = "trophytruck2", price = 100000, capacity = 20},
		},
	},
	{
		cat_name = "SUVs",
		value = "suvs",
		vehicles = {
			{name = "Baller", hash = "baller", price = 65000, capacity = 40},
			{name = "Baller 2", hash = "baller2", price = 95000, capacity = 50},
			{name = "Baller Sport", hash = "baller3", price = 125000, capacity = 40},
			{name = "Baller Sport 2", hash = "baller4", price = 135000, capacity = 50},
			{name = "BJ XL", hash = "bjxl", price = 115000, capacity = 50},	
			{name = "Cavalcade", hash = "cavalcade", price = 60000, capacity = 50},
			{name = "Cavalcade 2", hash = "cavalcade2", price = 75000, capacity = 50},
			{name = "Contender", hash = "contender", price = 150000, capacity = 60},
			{name = "Dubsta", hash = "dubsta", price = 65000, capacity = 55},
			{name = "Dubsta Luxuary", hash = "dubsta2", price = 75000, capacity = 55},
			{name = "FQ2", hash = "fq2", price = 50000, capacity = 40},
			{name = "Granger", hash = "granger", price = 100000, capacity = 50},
			{name = "Gresley", hash = "gresley", price = 55000, capacity = 40},
			{name = "Habanero", hash = "habanero", price = 50000, capacity = 40},
			{name = "Huntley", hash = "huntley", price = 75000, capacity = 40},
			{name = "Landstalker", hash = "landstalker", price = 65000, capacity = 45},
			{name = "Mesa", hash = "mesa", price = 35000, capacity = 55},
			{name = "Patriot", hash = "patriot", price = 200000, capacity = 40},
			{name = "Patriot 2", hash = "patriot2", price = 500000, capacity = 40},
			{name = "Radius", hash = "radi", price = 50000, capacity = 40},
			{name = "Rocoto", hash = "rocoto", price = 85000, capacity = 40},
			{name = "Seminole", hash = "seminole", price = 50000, capacity = 40},
			{name = "Toros", hash = "toros", price = 100000, capacity = 40},
			{name = "XLS", hash = "xls", price = 85000, capacity = 40},
		},
	},
	{
		cat_name = "Sedans",
		value = "sedans",
		vehicles = {
			{name = "Asea", hash = "asea", price = 15000, capacity = 35},
			{name = "Asterope", hash = "asterope", price = 17500, capacity = 35},
			{name = "Cognoscenti", hash = "cognoscenti", price = 70000, capacity = 35},
			{name = "Emperor", hash = "emperor", price = 17000, capacity = 30},
			{name = "Fugitive", hash = "fugitive", price = 20000, capacity = 35},
			{name = "Glendale", hash = "glendale", price = 13000, capacity = 35},
			{name = "ingot", hash = "ingot", price = 17000, capacity = 40},
			{name = "Intruder", hash = "intruder", price = 15000, capacity = 35},
			{name = "Premier", hash = "premier", price = 16000, capacity = 35},
			{name = "Primo", hash = "primo", price = 20000, capacity = 35},
			{name = "Primo Custom", hash = "primo2", price = 25000, capacity = 35},
			{name = "Regina", hash = "regina", price = 13000, capacity = 40},
			{name = "Stafford", hash = "stafford", price = 17500, capacity = 35},
			{name = "Stanier", hash = "stanier", price = 15000, capacity = 35},
			{name = "Stratum", hash = "stratum", price = 16000, capacity = 40},
			{name = "Stretch", hash = "stretch", price = 300000, capacity = 35},
			{name = "Super Diamond", hash = "superd", price = 200000, capacity = 35},
			{name = "Surge", hash = "surge", price = 17500, capacity = 35},
			{name = "Tailgater", hash = "tailgater", price = 38000, capacity = 35},
			{name = "Warrener", hash = "warrener", price = 15000, capacity = 35},
			{name = "Washington", hash = "washington", price = 13500, capacity = 35},
		},
	},
	{
		cat_name = "Sports",
		value = "sports",
		vehicles = {
			{name = "Alpha", hash = "alpha", price = 90000, capacity = 35},
			{name = "Banshee", hash = "banshee", price = 100000, capacity = 35},
			{name = "Bestia GTS", hash = "bestiagts", price = 110000, capacity = 35},
			{name = "Buffalo", hash = "buffalo", price = 35000, capacity = 35},
			{name = "Buffalo 2", hash = "buffalo2", price = 45000, capacity = 35},
			{name = "Buffalo 3", hash = "buffalo3", price = 40000, capacity = 35},
			{name = "Carbonizzare", hash = "carbonizzare", price = 110000, capacity = 20},
			{name = "Comet 2", hash = "comet2", price = 95000, capacity = 35},
			{name = "Comet 3", hash = "comet3", price = 97500, capacity = 35},
			{name = "Comet 4", hash = "comet4", price = 90000, capacity = 35},
			{name = "Comet 5", hash = "comet5", price = 115000, capacity = 35},
			{name = "Coquette", hash = "coquette", price = 95000, capacity = 35},
			{name = "Deveste", hash = "deveste", price = 135000, capacity = 20},
			{name = "Elegy", hash = "elegy", price = 95000, capacity = 35},
			{name = "Elegy 2", hash = "elegy2", price = 90000, capacity = 35},
			{name = "Feltzer 2", hash = "feltzer2", price = 85000, capacity = 35},
			{name = "Flash GT", hash = "flashgt", price = 70000, capacity = 35},
			{name = "Furore GT", hash = "furoregt", price = 70000, capacity = 35},
			{name = "Fusilade", hash = "fusilade", price = 60000, capacity = 35},
			{name = "Futo", hash = "futo", price = 55000, capacity = 35},
			{name = "GB200", hash = "gb200", price = 65000, capacity = 35},
			{name = "Hotring", hash = "hotring", price = 60000, capacity = 35},
			{name = "Itali GTO", hash = "italigto", price = 90000, capacity = 20},
			{name = "Jester", hash = "jester", price = 70000, capacity = 25},
			{name = "Jester 2", hash = "jester2", price = 60000, capacity = 25},
			{name = "Jester 3", hash = "jester3", price = 75000, capacity = 25},
			{name = "Khamelion", hash = "khamelion", price = 80000, capacity = 35},
			{name = "Kuruma", hash = "kuruma", price = 65000, capacity = 35},
			{name = "Lynx", hash = "lynx", price = 85000, capacity = 30},
			{name = "Massacro", hash = "massacro", price = 75000, capacity = 30},
			{name = "Massacro Racecar", hash = "massacro2", price = 70000, capacity = 30},
			{name = "Neon", hash = "neon", price = 95000, capacity = 35},
			{name = "9F", hash = "ninef", price = 90000, capacity = 30},
			{name = "9F Cabrio", hash = "ninef2", price = 95000, capacity = 30},
			{name = "Omnis", hash = "omnis", price = 55000, capacity = 25},
			{name = "Pariah", hash = "pariah", price = 90000, capacity = 30},
			{name = "Penumbra", hash = "penumbra", price = 65000, capacity = 30},
			{name = "Raiden", hash = "raiden", price = 75000, capacity = 30},
			{name = "Rapid GT", hash = "rapidgt", price = 70000, capacity = 30},
			{name = "Rapid GT 2", hash = "rapidgt2", price = 75000, capacity = 30},
			{name = "Raptor", hash = "raptor", price = 60000, capacity = 20},
			{name = "Ruston", hash = "ruston", price = 60000, capacity = 20},
			{name = "Schafter 2", hash = "schafter2", price = 55000, capacity = 35},
			{name = "Schafter 3", hash = "schafter3", price = 60000, capacity = 35},
			{name = "Schafter 4", hash = "schafter4", price = 70000, capacity = 35},
			{name = "Schlagen", hash = "schlagen", price = 115000, capacity = 35},
			{name = "Schwarzer", hash = "schwarzer", price = 65000, capacity = 35},
			{name = "Sentinel 3", hash = "sentinel3", price = 85000, capacity = 30},
			{name = "Seven 70", hash = "seven70", price = 75000, capacity = 30},
			{name = "Specter", hash = "specter", price = 65000, capacity = 35},
			{name = "Specter 2", hash = "specter2", price = 70000, capacity = 35},
			{name = "Streiter", hash = "streiter", price = 60000, capacity = 40},
			{name = "Sultan", hash = "sultan", price = 35000, capacity = 35},
			{name = "Surano", hash = "surano", price = 65000, capacity = 35},
			{name = "Tampa 2", hash = "tampa2", price = 55000, capacity = 35},
			{name = "Tropos", hash = "tropos", price = 60000, capacity = 35},
			{name = "Verlierer 2", hash = "verlierer2", price = 65000, capacity = 25},
		},
	},
	{
		cat_name = "Classic Sport",
		value = "classic_sport",
		vehicles = {
			{name = "Peyote", hash = "peyote", price = 55000, capacity = 25},
			{name = "Btype", hash = "btype", price = 125000, capacity = 30},
			{name = "B-Type Hotroad", hash = "btype2", price = 150000, capacity = 30},
			{name = "B-Type Luxe", hash = "btype3", price = 175000, capacity = 30},
			{name = "Casco", hash = "casco", price = 45000, capacity = 35},
			{name = "Cheetah 2", hash = "cheetah2", price = 200000, capacity = 30},
			{name = "Coquette 2", hash = "coquette2", price = 75000, capacity = 30},
			{name = "Fagaloa", hash = "fagaloa", price = 40000, capacity = 35},
			{name = "Feltzer 3", hash = "feltzer3", price = 50000, capacity = 30},
			{name = "GT500", hash = "gt500", price = 45000, capacity = 30},
			{name = "Infernus 2", hash = "infernus2", price = 42500, capacity = 30},
			{name = "Mamba", hash = "mamba", price = 40000, capacity = 30},
			{name = "Manana", hash = "manana", price = 25000, capacity = 25},
			{name = "Michelli", hash = "michelli", price = 20000, capacity = 30},
			{name = "Monroe", hash = "monroe", price = 65000, capacity = 30},
			{name = "Pigalle", hash = "pigalle", price = 30000, capacity = 35},
			{name = "Rapid GT 3", hash = "rapidgt3", price = 85000, capacity = 30},
			{name = "Retinue", hash = "retinue", price = 25000, capacity = 30},
			{name = "Stinger", hash = "stinger", price = 110000, capacity = 30},
			{name = "Stinger GT", hash = "stingergt", price = 120000, capacity = 30},
			{name = "Swinger", hash = "swinger", price = 80000, capacity = 25},
			{name = "Torero", hash = "torero", price = 75000, capacity = 25},
			{name = "Tornado", hash = "tornado", price = 35000, capacity = 35},
			{name = "Tornado 2", hash = "tornado2", price = 37500, capacity = 35},
			{name = "Tornado 3", hash = "tornado3", price = 30000, capacity = 35},
			{name = "Tornado 4", hash = "tornado4", price = 32500, capacity = 35},
			{name = "Tornado 5", hash = "tornado5", price = 40000, capacity = 30},
			{name = "Tornado 6", hash = "tornado6", price = 35000, capacity = 35},
			{name = "Turismo 2", hash = "turismo2", price = 80000, capacity = 30},
			{name = "Z190", hash = "z190", price = 75000, capacity = 30},
			{name = "Z-Type", hash = "ztype", price = 115000, capacity = 25},
			{name = "Cheburek", hash = "cheburek", price = 35000, capacity = 30},
		},
		
	},
	{
		cat_name = "Super",
		value = "super",
		vehicles = {
			{name = "Adder", hash = "adder", price = 450000, capacity = 25},
			{name = "Autarch", hash = "autarch", price = 350000, capacity = 25},
			{name = "Banshee 2", hash = "banshee2", price = 370000, capacity = 25},
			{name = "Bullet", hash = "bullet", price = 150000, capacity = 25},
			{name = "Cheetah", hash = "cheetah", price = 375000, capacity = 25},
			{name = "Cyclone", hash = "cyclone", price = 180000, capacity = 25},
			{name = "Entity 2", hash = "entity2", price = 375000, capacity = 25},
			{name = "Entity FX", hash = "entityfx", price = 400000, capacity = 25},
			{name = "FMJ", hash = "fmj", price = 275000, capacity = 25},
			{name = "Infernus", hash = "infernus", price = 225000, capacity = 25},
			{name = "Itali GTB", hash = "italigtb", price = 325000, capacity = 25},
			{name = "Itali GTB 2", hash = "italigtb2", price = 350000, capacity = 25},
			{name = "LE7B", hash = "le7b", price = 225000, capacity = 25},
			{name = "Nero", hash = "nero", price = 400000, capacity = 25},
			{name = "Nero 2", hash = "nero2", price = 425000, capacity = 25},
			{name = "Osiris", hash = "osiris", price = 375000, capacity = 25},
			{name = "Penetrator", hash = "penetrator", price = 225000, capacity = 25},
			{name = "PFister811", hash = "pfister811", price = 300000, capacity = 25},
			{name = "Prototipo", hash = "prototipo", price = 425000, capacity = 25},
			{name = "Reaper", hash = "reaper", price = 325000, capacity = 25},
			{name = "SC1", hash = "sc1", price = 300000, capacity = 35},
			{name = "Sheava", hash = "sheava", price = 275000, capacity = 35},
			{name = "Sultan RS", hash = "sultanrs", price = 150000, capacity = 35},
			{name = "T20", hash = "t20", price = 250000, capacity = 35},
			{name = "Taipan", hash = "taipan", price = 325000, capacity = 35},
			{name = "Tempesta", hash = "tempesta", price = 300000, capacity = 35},
			{name = "Tezeract", hash = "tezeract", price = 425000, capacity = 35},
			{name = "Turismo R", hash = "turismor", price = 325000, capacity = 35},
			{name = "Tyran T", hash = "tyrant", price = 375000, capacity = 35},
			{name = "Tyrus", hash = "tyrus", price = 275000, capacity = 35},
			{name = "Vacca", hash = "vacca", price = 325000, capacity = 35},
			{name = "Vagner", hash = "vagner", price = 275000, capacity = 35},
			{name = "Visione", hash = "visione", price = 325000, capacity = 35},
			{name = "Voltic", hash = "voltic", price = 300000, capacity = 35},
			{name = "XA21", hash = "xa21", price = 350000, capacity = 35},
			{name = "Zentorno", hash = "zentorno", price = 375000, capacity = 35},
		},
	},
	{
		cat_name = "Utility",
		value = "utility",
		vehicles = {
			{name = "Sadler", hash = "sadler", price = 75000, capacity = 50},
			{name = "Scrap", hash = "scrap", price = 60000, capacity = 50},
			{name = "Towtruck", hash = "towtruck", price = 50000, capacity = 35},
			{name = "Towtruck 2", hash = "towtruck2", price = 60000, capacity = 30},
		},
	},
	{
		cat_name = "Vans",
		value = "vans",
		vehicles = {
			{name = "Bison", hash = "bison", price = 65000, capacity = 45},	
			{name = "Bison 2", hash = "bison2", price = 70000, capacity = 45},
			{name = "Bison 3", hash = "bison3", price = 75000, capacity = 45},
			{name = "Bobcat XL", hash = "bobcatxl", price = 50000, capacity = 45},
			{name = "Burrito", hash = "burrito", price = 40000, capacity = 50},
			{name = "Burrito 2", hash = "burrito2", price = 42500, capacity = 50},
			{name = "Burrito 3", hash = "burrito3", price = 45000, capacity = 50},
			{name = "Burrito 4", hash = "burrito4", price = 42500, capacity = 50},
			{name = "Camper", hash = "camper", price = 60000, capacity = 45},
			{name = "Gang Burrito 2", hash = "gburrito2", price = 65000, capacity = 50},
			{name = "Journey", hash = "journey", price = 50000, capacity = 45},
			{name = "Minivan", hash = "minivan", price = 65000, capacity = 40},
			{name = "Minivan 2", hash = "minivan2", price = 70000, capacity = 40},
			{name = "Paradise", hash = "paradise", price = 45000, capacity = 45},
			{name = "Pony", hash = "pony", price = 45000, capacity = 45},
			{name = "Pony 2", hash = "pony2", price = 50000, capacity = 45},
			{name = "Rumpo", hash = "rumpo", price = 60000, capacity = 50},
			{name = "Rumpo 2", hash = "rumpo2", price = 60000, capacity = 50},
			{name = "Rumpo 3", hash = "rumpo3", price = 75000, capacity = 50},
			{name = "Speedo", hash = "speedo", price = 55000, capacity = 50},
			{name = "Speedo 4", hash = "speedo4", price = 60000, capacity = 50},
			{name = "Surfer", hash = "surfer", price = 65000, capacity = 35},
			{name = "Surfer 2", hash = "surfer2", price = 50000, capacity = 35},
			{name = "Youga", hash = "youga", price = 65000, capacity = 50},
			{name = "Youga Luxuary", hash = "youga2", price = 60000, capacity = 50},
		},	
	},
	{
		cat_name = "Velo",
		value = "velo",
		vehicles = {
			{name = "BMX", hash = "bmx", price = 500},
			{name = "Cruiser", hash = "cruiser", price = 500},
			{name = "Fixter", hash = "fixter", price = 750},
			{name = "Scorcher", hash = "scorcher", price = 1000},
			{name = "Tribike", hash = "tribike", price = 1250},
			{name = "Tribike 2", hash = "tribike2", price = 1250},
			{name = "Tribike 3", hash = "tribike3", price = 1250},
		},	
	},
}

function AddVehicleToPlayer(model, xPlayer)
    local veh_plate = CreateRandomPlateText()
    print(veh_plate)
    MySQL.Async.execute("INSERT INTO owned_vehicles (owner, plate, vehicle, type, state, boutique, selling) VALUES(@owner, @plate, @vehicle, 'car', 0, 0, 0)", {
        ["@owner"] = xPlayer.identifier,
        ["@plate"] = veh_plate,
        ["@vehicle"] = json.encode({ model = GetHashKey(model), plate = veh_plate })
    }, function(owned_vehicles)
        if owned_vehicles then
            MySQL.Async.execute("INSERT INTO open_car (owner, plate, NB) VALUES(@owner, @plate, 0)", {
                ["@owner"] = xPlayer.identifier,
                ["@plate"] = veh_plate
            }, function(open_car)
                if open_car then
                    SetEntityCoords(GetPlayerPed(xPlayer.source), -763.220703125, -250.23156738281, 37.09511184692)
                    local vehicleGived = CreateVehicle(GetHashKey(model), -763.220703125, -250.23156738281, 37.095111846924, 108.0, true, false)
                    TaskWarpPedIntoVehicle(GetPlayerPed(xPlayer.source), vehicleGived, -1)
                    SetVehicleNumberPlateText(vehicleGived, veh_plate)
                end
            end)
        end
    end)
end

Alma:AddEventHandler("Carsales", "BucketEnter", function()
	SetPlayerRoutingBucket(source, math.random(1, 10000000))
end)

Alma:AddEventHandler("Carsales", "BucketExit", function()
	SetPlayerRoutingBucket(source, 0)
end)

Alma:AddEventHandler("Luxury", "PayNewVehicle", function(modelVeh)
    local source = source;
    local xPlayer = ESX.GetPlayerFromId(source);

    for l,k in pairs(Concess.vehicles) do
        for i,v in pairs(k.vehicles) do
            if modelVeh == v.hash then
                if xPlayer.getAccount('bank').money >= v.price then
					SetPlayerRoutingBucket(source, 0)
                    xPlayer.removeAccountMoney('bank', v.price)
                    xPlayer.showNotification("Payée par compte en banque:\n~r~- "..ESX.Math.GroupDigits(v.price).."$")
                    AddVehicleToPlayer(v.hash, xPlayer)
                    Helper:showAdvancedNotification(source, "Concessionnaire", "Luxury Motors", "Bonjour, ~g~merci de votre achat chez nous~s~, voici les clés de votre ~g~"..v.name.."~s~, bonne route !", "CHAR_MALC", 1)
                else
                    if xPlayer.getAccount('money').money >= v.price then
						SetPlayerRoutingBucket(source, 0)
                        xPlayer.removeAccountMoney('money', v.price)
                        xPlayer.showNotification("Payée en liquide:\n~r~-"..ESX.Math.GroupDigits(v.price).."$")
                        AddVehicleToPlayer(v.hash, xPlayer)
                        Helper:showAdvancedNotification(source, "Concessionnaire", "Luxury Motors", "Bonjour, ~g~merci de votre achat chez nous~s~, voici les clés de votre ~g~"..v.name.."~s~, bonne route !", "CHAR_MALC", 1)
                    else
                        xPlayer.showNotification("Vous n'avez pas assez pour acheter "..v.name.." ~r~(requis "..v.price..")~s~")
                    end
                end
            end
        end
    end
end)